"""
IDA Pro Symbol Resolver Script
================================
This script loads modules.json and symbols.json generated by SymbolDumper,
then scans the currently loaded binary in IDA for address-related data
(4-byte and 8-byte pointer values). When a match is found, it applies
symbol names and comments.

Usage in IDA:
  1. File -> Script file... -> select this script
  2. Or: Alt+F7 -> select this script
  3. Or: from IDA Python console:
     exec(open(r"path/to/ida_symbol_resolver.py").read())

The script will prompt for the JSON file paths via dialog.
"""

import json
import os
import struct
import time

# ===================================================================
# Global Configuration
# ===================================================================
ENABLE_RENAME = True   # Set to False to disable all rename operations (only apply comments)

try:
    import idaapi
    import idautils
    import idc
    import ida_bytes
    import ida_name
    import ida_kernwin
    import ida_ida
    IN_IDA = True
except ImportError:
    IN_IDA = False
    print("[!] This script must be run inside IDA Pro.")


def load_json_file(path):
    """Load and parse a JSON file."""
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def parse_hex(val):
    """Parse a hex string like '0x1234' to int."""
    if isinstance(val, int):
        return val
    if isinstance(val, str):
        return int(val, 16)
    return 0


class SymbolDatabase:
    """Holds all symbol information from the JSON dump."""

    def __init__(self):
        self.modules = []           # List of module dicts
        self.addr_to_symbol = {}    # address -> symbol info
        self.rva_to_symbol = {}     # (module_name, rva) -> symbol info
        self.all_addresses = set()  # All known addresses for fast lookup
        self.all_rvas = {}          # module_base -> list of (rva, symbol)

    def load(self, modules_json_path, symbols_json_path):
        """Load modules and symbols from JSON files."""
        modules_data = load_json_file(modules_json_path)
        symbols_data = load_json_file(symbols_json_path)

        self.modules = modules_data.get("modules", [])
        process_name = modules_data.get("process_name", "unknown")
        process_pid = modules_data.get("process_id", 0)

        print(f"[SymbolDumper] Process: {process_name} (PID: {process_pid})")
        print(f"[SymbolDumper] Modules: {len(self.modules)}")

        total_syms = 0
        for mod_syms in symbols_data.get("modules", []):
            module_name = mod_syms.get("module_name", "")
            base_addr = parse_hex(mod_syms.get("base_address", "0"))

            symbols = mod_syms.get("symbols", [])
            total_syms += len(symbols)

            rva_list = []
            for sym in symbols:
                name = sym.get("name", "")
                rva = parse_hex(sym.get("rva", "0"))
                addr = parse_hex(sym.get("address", "0"))
                sym_type = sym.get("type", "")
                source = sym.get("source", "")
                library = sym.get("library", "")

                info = {
                    "name": name,
                    "module": module_name,
                    "rva": rva,
                    "address": addr,
                    "type": sym_type,
                    "source": source,
                    "library": library,
                }

                if addr != 0:
                    self.addr_to_symbol[addr] = info
                    self.all_addresses.add(addr)

                rva_list.append((rva, info))

            if base_addr != 0:
                self.all_rvas[base_addr] = rva_list

        print(f"[SymbolDumper] Total symbols loaded: {total_syms}")
        print(f"[SymbolDumper] Unique addresses: {len(self.all_addresses)}")

    def lookup_address(self, addr):
        """Look up a symbol by absolute address."""
        return self.addr_to_symbol.get(addr, None)


def sanitize_name(name):
    """
    Sanitize a symbol name for IDA.
    IDA names can contain: letters, digits, underscore, dollar sign.
    """
    result = []
    for ch in name:
        if ch.isalnum() or ch in ('_', '$', '.'):
            result.append(ch)
        elif ch in (' ', '-', '+', '@', '?', ':'):
            result.append('_')
        else:
            result.append('_')
    s = ''.join(result)
    # IDA names cannot start with a digit
    if s and s[0].isdigit():
        s = '_' + s
    return s


def make_unique_name(base_name, module_name):
    """Create a qualified symbol name: module!symbol."""
    # Remove file extension from module name
    mod = module_name
    dot = mod.rfind('.')
    if dot > 0:
        mod = mod[:dot]

    qualified = f"{sanitize_name(mod)}__{sanitize_name(base_name)}"
    return qualified


def _rename_pointer_location(ea, sym):
    """Rename a pointer location to reflect the symbol it points to."""
    current_name = idc.get_name(ea)
    if current_name and not current_name.startswith(("off_", "qword_", "dword_", "unk_")):
        return False
    ptr_name = f"ptr_{sanitize_name(sym['module'].split('.')[0])}__{sanitize_name(sym['name'])}"
    return ida_name.set_name(ea, ptr_name, ida_name.SN_NOWARN | ida_name.SN_NOCHECK)


def scan_binary(db):
    """
    Scan the loaded binary in IDA for pointer-sized values that match
    known symbol addresses. Apply names and comments where found.
    """
    if not IN_IDA:
        print("[!] Not running in IDA.")
        return

    is_64 = ida_ida.inf_is_64bit()
    ptr_size = 8 if is_64 else 4

    print(f"\n[SymbolDumper] Binary: {'64-bit' if is_64 else '32-bit'} (ptr_size={ptr_size})")

    # Get the image base of the currently loaded binary
    image_base = ida_ida.inf_get_min_ea() & ~0xFFF  # fallback
    try:
        image_base = idaapi.get_imagebase()
    except:
        pass
    print(f"[SymbolDumper] Image base: {image_base:#x}")

    # Check if this binary's base matches any module
    matching_module = None
    for mod in db.modules:
        mod_base = parse_hex(mod.get("base_address", "0"))
        if mod_base == image_base:
            matching_module = mod
            break

    if matching_module:
        print(f"[SymbolDumper] Current binary matches module: {matching_module.get('name', '?')}")

    # ---------------------------------------------------------------
    # Phase 1: Apply symbols to the current module if bases match
    # ---------------------------------------------------------------
    phase1_count = 0

    if matching_module:
        mod_name = matching_module.get("name", "")
        mod_base = parse_hex(matching_module.get("base_address", "0"))

        for addr, sym in db.addr_to_symbol.items():
            if sym["module"] != mod_name:
                continue

            rva = sym["rva"]
            ea = image_base + rva

            # Check if this address is within the loaded segments
            if not is_loaded(ea):
                continue

            name = sanitize_name(sym["name"])
            source = sym["source"]
            sym_type = sym["type"]

            # Set name
            if ENABLE_RENAME:
                current_name = idc.get_name(ea)
                if not current_name or current_name.startswith("sub_") or \
                   current_name.startswith("loc_") or current_name.startswith("unk_"):
                    if ida_name.set_name(ea, name, ida_name.SN_NOWARN | ida_name.SN_NOCHECK):
                        phase1_count += 1

            # Add comment with full info
            comment = f"[SD] {sym['module']}!{sym['name']} ({source}, {sym_type})"
            if sym["library"]:
                comment += f" from {sym['library']}"
            idc.set_cmt(ea, comment, 0)

    print(f"[SymbolDumper] Phase 1 - Direct symbol application: {phase1_count} symbols applied")

    # ---------------------------------------------------------------
    # Phase 2: Scan binary data for pointer values matching known
    #          addresses (4-byte and 8-byte scans)
    # ---------------------------------------------------------------
    phase2_count = 0
    scan_count = 0

    if not db.all_addresses:
        print("[SymbolDumper] Phase 2 - No addresses to scan for.")
        return

    # Build a set for fast lookup
    addr_set = db.all_addresses

    # Determine scan sizes
    scan_sizes = [4, 8] if is_64 else [4]

    print(f"[SymbolDumper] Phase 2 - Scanning segments for {len(addr_set)} known addresses...")

    start_time = time.time()

    for seg_ea in idautils.Segments():
        seg_start = idc.get_segm_start(seg_ea)
        seg_end = idc.get_segm_end(seg_ea)
        seg_name = idc.get_segm_name(seg_ea)

        print(f"  Scanning segment: {seg_name} ({seg_start:#x} - {seg_end:#x})")

        ea = seg_start
        while ea <= seg_end - 4:
            scan_count += 1

            # Read 4-byte value
            val32 = ida_bytes.get_dword(ea)
            if val32 in addr_set:
                sym = db.lookup_address(val32)
                if sym:
                    comment = f"[SD] -> {sym['module']}!{sym['name']} (RVA:{sym['rva']:#x}, {sym['source']})"
                    old_cmt = idc.get_cmt(ea, 0) or ""
                    if "[SD]" not in old_cmt:
                        idc.set_cmt(ea, comment, 0)
                        if ENABLE_RENAME:
                            _rename_pointer_location(ea, sym)
                        phase2_count += 1

            # Read 8-byte value (only for 64-bit or if scanning both)
            if is_64 and ea <= seg_end - 8:
                val64 = ida_bytes.get_qword(ea)
                if val64 != val32 and val64 in addr_set:
                    sym = db.lookup_address(val64)
                    if sym:
                        comment = f"[SD] -> {sym['module']}!{sym['name']} (RVA:{sym['rva']:#x}, {sym['source']})"
                        old_cmt = idc.get_cmt(ea, 0) or ""
                        if "[SD]" not in old_cmt:
                            idc.set_cmt(ea, comment, 0)
                            if ENABLE_RENAME:
                                _rename_pointer_location(ea, sym)
                            phase2_count += 1

            ea += ptr_size  # Advance by pointer size for aligned scan

    elapsed = time.time() - start_time
    print(f"\n[SymbolDumper] Phase 2 - Pointer scan complete:")
    print(f"  Scanned {scan_count} locations in {elapsed:.2f}s")
    print(f"  Found {phase2_count} pointer matches")


def is_loaded(ea):
    """Check if an address is loaded in IDA."""
    return ida_bytes.is_loaded(ea)


def scan_unaligned(db, step=1):
    """
    Optional: Byte-by-byte scan for unaligned pointer values.
    This is slower but catches more matches. Use with caution on large binaries.
    """
    if not IN_IDA:
        return

    is_64 = ida_ida.inf_is_64bit()
    addr_set = db.all_addresses
    match_count = 0

    print(f"\n[SymbolDumper] Unaligned scan (step={step})...")

    for seg_ea in idautils.Segments():
        seg_start = idc.get_segm_start(seg_ea)
        seg_end = idc.get_segm_end(seg_ea)

        ea = seg_start
        while ea <= seg_end - 4:
            val32 = ida_bytes.get_dword(ea)
            if val32 in addr_set:
                sym = db.lookup_address(val32)
                if sym:
                    old_cmt = idc.get_cmt(ea, 0) or ""
                    if "[SD]" not in old_cmt:
                        comment = f"[SD:unaligned] -> {sym['module']}!{sym['name']}"
                        idc.set_cmt(ea, comment, 0)
                        match_count += 1

            if is_64 and ea <= seg_end - 8:
                val64 = ida_bytes.get_qword(ea)
                if val64 in addr_set:
                    sym = db.lookup_address(val64)
                    if sym:
                        old_cmt = idc.get_cmt(ea, 0) or ""
                        if "[SD]" not in old_cmt:
                            comment = f"[SD:unaligned] -> {sym['module']}!{sym['name']}"
                            idc.set_cmt(ea, comment, 0)
                            match_count += 1

            ea += step

    print(f"[SymbolDumper] Unaligned scan: {match_count} additional matches")


def apply_all_module_symbols(db):
    """
    Apply symbol names for ALL modules, computing RVA-based addresses
    relative to the current image base. Useful when the loaded binary
    is one of the dumped modules.
    """
    if not IN_IDA:
        return

    image_base = idaapi.get_imagebase()
    count = 0

    for addr, sym in db.addr_to_symbol.items():
        rva = sym["rva"]
        ea = image_base + rva

        if not is_loaded(ea):
            continue

        name = sanitize_name(sym["name"])
        current_name = idc.get_name(ea)

        if ENABLE_RENAME:
            if not current_name or current_name.startswith("sub_") or \
               current_name.startswith("loc_") or current_name.startswith("unk_"):
                qualified = make_unique_name(sym["name"], sym["module"])
                if ida_name.set_name(ea, name, ida_name.SN_NOWARN | ida_name.SN_NOCHECK):
                    count += 1
                elif ida_name.set_name(ea, qualified, ida_name.SN_NOWARN | ida_name.SN_NOCHECK):
                    count += 1

        comment = f"[SD] {sym['module']}!{sym['name']} ({sym['source']})"
        idc.set_cmt(ea, comment, 0)

    print(f"[SymbolDumper] Applied {count} symbols from all modules")


# ===================================================================
# Main entry point
# ===================================================================

def main():
    if not IN_IDA:
        print("This script must be run inside IDA Pro.")
        print("Usage: File -> Script file... -> select this script")
        return

    print("=" * 60)
    print("  SymbolDumper - IDA Symbol Resolver")
    print("=" * 60)

    # Ask for JSON file paths
    modules_path = ida_kernwin.ask_file(False, "*.json", "Select modules.json")
    if not modules_path:
        print("[!] No modules.json selected. Aborting.")
        return

    symbols_path = ida_kernwin.ask_file(False, "*.json", "Select symbols.json")
    if not symbols_path:
        print("[!] No symbols.json selected. Aborting.")
        return

    # Load symbol database
    db = SymbolDatabase()
    try:
        db.load(modules_path, symbols_path)
    except Exception as e:
        print(f"[!] Error loading JSON: {e}")
        return

    # Ask user what to do
    choice = ida_kernwin.ask_buttons(
        "Full Scan",        # Button 1
        "Apply Symbols",    # Button 2
        "Cancel",           # Button 3
        1,                  # Default
        "SymbolDumper Actions:\n\n"
        "- Full Scan: Apply symbols + scan for pointer matches\n"
        "- Apply Symbols: Only apply symbol names (no pointer scan)\n"
    )

    if choice == 1:
        # Full scan
        scan_binary(db)

        # Ask about unaligned scan
        do_unaligned = ida_kernwin.ask_yn(
            0,
            "Run unaligned byte-by-byte scan?\n"
            "(This is slower but catches more matches)"
        )
        if do_unaligned == 1:
            scan_unaligned(db)

    elif choice == 0:
        # Apply symbols only
        apply_all_module_symbols(db)

    else:
        print("[*] Cancelled.")
        return

    print("\n" + "=" * 60)
    print("  SymbolDumper - Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()
